export const TYPES = {
  CALL_API: 'FETCH_SUCESS',
  ADD_ONE: 'ADD_ONE',
  REMOVE_ONE: 'REMOVE_ONE',
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_ONE_IN_CART: 'ADD_ONE_IN_CART',
  REMOVE_ONE_IN_CART: 'REMOVE_ONE_IN_CART',
  CLEAR_CART: 'CLEAR_CART',
  OFF__LOADER: 'OFF_LOADER'
}